### ISSUE TITLE
Cannot process argument transformation on parameter 'RootPublicKey'. Cannot convert value to type System.String.

### ISSUE THREAD

**Issue by paulhermanseu** [fdcastel/Hyper-V-Automation#2]
When I provide multiple SSH keys via RootPublicKey using array syntax value1,value2 I get this Error:

New-VMFromUbuntuImage.ps1 : Cannot process argument transformation on parameter 'RootPublicKey'. Cannot convert value to type System.String.

Example: -RootPublicKey 'ssh-rsa AAABBBCCC...','ssh-rsa DDDEEEFFF...'

I tested with both keys on two separate VM creations and that works perfect.

What could be the problem?

**Comment by fdcastel** [comment]
Sorry for the lack of support @paulhermanseu 😢. I just keep theses scripts here for my usage (and to others benefit) but my time is very limited to provide anything else.

As of now you probably already did notice that the `RootPublicKey` accepts only _one_ key instead of multiple values.

If you need this feature, please send me a PR.
